version: "2"
run:
  tests: false
  timeout: 5m
  go: "1.24.0"
  modules-download-mode: readonly
formatters:
  enable:
    - gofmt
    - goimports
linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - dogsled
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
#    - forcetypeassert
    - goconst
    - gocritic
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
#    - gosimple // Invalid
    - govet
    - grouper
    - importas
    - ineffassign
#    - ireturn
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
#    - noctx - // TODO: Enable (SQLite package)
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
#    - promlinter // TODO: Enable
#    - revive // TODO: Enable
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usetesting
    - whitespace
    # Ignored for now, but we should enable it in the future
    - wrapcheck
#    - gocognit
    - dupl
#    - gocyclo
#    - maintidx
