{
 "title": "Cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "promds", "label": "Prometheus Data Source", "query": "prometheus" },
   {
    "name": "infds",
    "label": "Infinity DataSource",
    "query": "yesoreyeram-infinity-datasource"
   },
   {
    "name": "recods",
    "label": "Recommendation Data Source",
    "query": "yesoreyeram-infinity-datasource"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Used / Allocated %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum by (node) (\n    rate(container_cpu_usage_seconds_total{container!~\"POD|\",job=\"kubelet\"}[1m])\n  )\n  unless sum by (node) (kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n)\n/\n(\n  sum(\n    sum by (node) (\n      kube_node_status_allocatable{container!=\"\",job=\"kube-state-metrics\",resource=\"cpu\"}\n    )\n    unless sum by (node) (kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n  )\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Requested / Allocated %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(\n      sum by (node) (\n            sum by (namespace, pod, node) (\n              kube_pod_container_resource_requests{container!=\"\",job=\"kube-state-metrics\",resource=\"cpu\"}\n            )\n          * on (namespace, pod) group_left ()\n            max by (namespace, pod) (kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"} > 0)\n        * on (namespace, pod) group_left ()\n          max by (namespace, pod) (\n            kube_pod_info{created_by_name!=\"autopilot-pause-daemonset\",job=\"kube-state-metrics\"}\n          )\n      )\n    unless\n      sum by (node) (kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0)\n  )\n)\n/\n(\n  sum(\n    sum by (node) (\n      kube_node_status_allocatable{container!=\"\",job=\"kube-state-metrics\",resource=\"cpu\"}\n    )\n    unless sum by (node) (kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n  )\n) * 100",
     "legendFormat": "Used / Requested %"
    }
   ]
  },
  {
   "title": "CPU Used / Requested %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum by (node) (\n    rate(container_cpu_usage_seconds_total{container!~\"POD|\",job=\"kubelet\"}[1m])\n  )\n  unless sum by (node) (kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n)\n/\n(\n  sum(\n      sum by (node) (\n            sum by (namespace, pod, node) (\n              kube_pod_container_resource_requests{container!=\"\",job=\"kube-state-metrics\",resource=\"cpu\"}\n            )\n          * on (namespace, pod) group_left ()\n            max by (namespace, pod) (kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"} > 0)\n        * on (namespace, pod) group_left ()\n          max by (namespace, pod) (\n            kube_pod_info{created_by_name!=\"autopilot-pause-daemonset\",job=\"kube-state-metrics\"}\n          )\n      )\n    unless\n      sum by (node) (kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0)\n  )\n) * 100",
     "legendFormat": "Used / Requested %"
    }
   ]
  },
  {
   "title": "Memory Used / Allocated %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n      sum(\n            sum by (namespace, node, pod) (\n              container_memory_working_set_bytes{container!~\"POD|\",job=\"kubelet\"}\n            )\n        unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n      ) / (1000*1000*1000))\n/\n((\n          sum(\n                sum by (namespace, pod, node) (\n                  kube_node_status_allocatable{container!=\"\",job=\"kube-state-metrics\",resource=\"memory\"}\n                )\n          unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n        )\n      ) / (1000*1000*1000))\n*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Used / Requested %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "    (\n        sum(\n            sum by (namespace, node, pod) (container_memory_working_set_bytes{container!~\"POD|\",job=\"kubelet\"})\n          unless\n            sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0)\n        )\n      /\n        (1000 * 1000 * 1000)\n    )\n  /\n    (\n        sum(\n          (\n            sum(\n                  sum by (namespace, pod, node) (\n                    kube_pod_container_resource_requests{container!=\"\",job=\"kube-state-metrics\",resource=\"memory\"}\n                  )\n                * on (namespace, pod) group_left ()\n                  max by (namespace, pod) (kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"} > 0)\n              unless\n                sum(kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0)\n            )\n          )\n        )\n      /\n        (1000 * 1000 * 1000)\n    )\n*\n  100",
     "legendFormat": "Used / Requested %"
    }
   ]
  },
  {
   "title": "Memory Requested / Allocated %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(  (\n      (\n          sum(\n                sum by (namespace, pod, node) (\n                  kube_pod_container_resource_requests{container!=\"\",job=\"kube-state-metrics\",resource=\"memory\"}\n                )\n              * on (namespace, pod) group_left ()\n                max by (namespace, pod) (kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"} > 0)\n          unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n        )\n      )\n  ) / (1000*1000*1000))\n/\n((\n          sum(\n                sum by (namespace, pod, node) (\n                  kube_node_status_allocatable{container!=\"\",job=\"kube-state-metrics\",resource=\"memory\"}\n                )\n          unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n        )\n      ) / (1000*1000*1000))\n* 100",
     "legendFormat": "Used / Requested %"
    }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    (sum by (node) (kube_pod_status_phase{job=\"kube-state-metrics\",phase=~\"Running\"}))\n  unless\n    (\n      sum by (node) (kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0)\n    )\n)",
     "legendFormat": "Used / Requested %"
    }
   ]
  },
  {
   "title": "Nodes count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  (\n      count by (node) (kube_node_labels{job=\"kube-state-metrics\"})\n    unless\n      (\n        sum by (node) (kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0)\n      )\n  )\n)",
     "legendFormat": "Used / Requested %"
    }
   ]
  },
  {
   "title": "Current total CPU request",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"summary\"\n| project \"total_current_cpu_requests\"",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Enabling autopilot will reduce CPU by",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"summary\"\n| project \"total_cpu_differences\"",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Current total Memory request (GB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"summary\"\n| project div(\"total_current_memory_requests\",1000)",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Enabling autopilot will reduce memory by",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json\n| scope \"summary\"\n| project div(\"total_memory_differences\",1000)",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "CPU Utilised / Requested / Allocatable",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(\n  sum by (node) (\n    rate(container_cpu_usage_seconds_total{container!~\"POD|\",job=\"kubelet\"}[1m])\n  )\n  unless sum by (node) (kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n)",
     "legendFormat": "Utilised"
    },
    {
     "expr": "(\n  sum(\n      sum by (node) (\n            sum by (namespace, pod, node) (\n              kube_pod_container_resource_requests{container!=\"\",job=\"kube-state-metrics\",resource=\"cpu\"}\n            )\n          * on (namespace, pod) group_left ()\n            max by (namespace, pod) (kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"} > 0)\n        * on (namespace, pod) group_left ()\n          max by (namespace, pod) (\n            kube_pod_info{created_by_name!=\"autopilot-pause-daemonset\",job=\"kube-state-metrics\"}\n          )\n      )\n    unless\n      sum by (node) (kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0)\n  )\n)",
     "legendFormat": "Requested"
    },
    {
     "expr": "(\n  sum(\n    sum by (node) (\n      kube_node_status_allocatable{container!=\"\",job=\"kube-state-metrics\",resource=\"cpu\"}\n    )\n    unless sum by (node) (kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n  )\n)",
     "legendFormat": "Allocatable"
    }
   ]
  },
  {
   "title": "Memory Utilised / Requested / Allocatable",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "(\n  sum(\n    sum by (node) (\n      container_memory_working_set_bytes{container!~\"POD|\",job=\"kubelet\"}\n    )\n    unless sum by (node) (kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n  ) / (1000*1000*1000))",
     "legendFormat": "Utilised"
    },
    {
     "expr": "(\n        (\n          sum(\n              sum by (node) (\n                    sum by (namespace, pod, node) (\n                      kube_pod_container_resource_requests{container!=\"\",job=\"kube-state-metrics\",resource=\"memory\"}\n                    )\n                  * on (namespace, pod) group_left ()\n                    max by (namespace, pod) (kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"} > 0)\n                * on (namespace, pod) group_left ()\n                  max by (namespace, pod) (\n                    kube_pod_info{created_by_name!=\"autopilot-pause-daemonset\",job=\"kube-state-metrics\"}\n                  )\n              )\n            unless\n              sum by (node) (kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0)\n          )\n        )\n      /\n        (1000 * 1000 * 1000)\n    )",
     "legendFormat": "Requested"
    },
    {
     "expr": "((\n  sum(\n    sum by (node) (\n                  kube_node_status_allocatable{container!=\"\",job=\"kube-state-metrics\",resource=\"memory\"}\n                )\n    unless sum by (node) (kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} > 0)\n  )\n) / (1000*1000*1000))",
     "legendFormat": "Allocatable"
    }
   ]
  },
  {
   "title": "Node CPU",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum by (node) (\n  sum by (namespace, pod, node) (\n    kube_pod_container_resource_requests{container!=\"\",job=\"kube-state-metrics\",resource=\"cpu\"}\n  )\n  * on (namespace, pod) group_left ()\n    max by (namespace, pod) (kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"} > 0)\n  * on (namespace, pod) group_left ()\n    max by (namespace, pod) (\n      kube_pod_info{created_by_name!=\"autopilot-pause-daemonset\",job=\"kube-state-metrics\"}\n    )\n  )\nunless\n  (sum by (node) (kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0))",
     "legendFormat": "Space {{node}}"
    },
    {
     "expr": "(sum by (node, core) (kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"cpu\"})\n- on (node) group_left ()\n(\n  sum by (node) (\n    sum by (namespace, pod, node) (\n      kube_pod_container_resource_requests{container!=\"\",job=\"kube-state-metrics\",resource=\"cpu\"}\n    )\n    * on (namespace, pod) group_left ()\n    max by (namespace, pod) (kube_pod_status_phase{job=\"kube-state-metrics\",phase=\"Running\"} > 0)\n    * on (namespace, pod) group_left ()\n    max by (namespace, pod) (\n      kube_pod_info{created_by_name!=\"autopilot-pause-daemonset\",job=\"kube-state-metrics\"}\n    )\n  )\n))\nunless\n  (sum by (node) (kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0))",
     "legendFormat": "Requested {{node}}"
    }
   ]
  },
  {
   "title": "Pod level analysis",
   "type": "table",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "columns": [
      { "selector": "workload_namespace", "text": "Namespace", "type": "string" },
      { "selector": "workload_name", "text": "Name", "type": "string" },
      { "selector": "container_name", "text": "Container", "type": "string" },
      {
       "selector": "cpu_usage_7_days",
       "text": "CPU usage 7d (pmax/p99/p90/p75/p50)",
       "type": "string"
      },
      { "selector": "spiky_ratio", "text": "Spiky Ratio", "type": "string" },
      {
       "selector": "contribution_to_total_requested",
       "text": "Contribution %",
       "type": "string"
      },
      { "selector": "priority", "text": "Priority", "type": "string" },
      { "selector": "autoscaling_on_cpu", "text": "CPU autoscaled", "type": "boolean" },
      { "selector": "workload_type", "text": "Type", "type": "string" }
     ],
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json \n| scope \"analysis\"\n| extend \"Workload\"=strcat(\"workload_type\", '/', \"workload_name\")\n| project \"Namespace\"=\"workload_namespace\", \"Workload\", \"Pod Name\"=\"pod_name\", \"Container\"=\"container_name\", \"CPU usage 7d (pmax/p99/p90/p75/p50)\"=\"cpu_usage_7_days\", \"CPU autoscaled\"=\"autoscaling_on_cpu\", \"Blocking Karpenter\"=\"blocking_karpenter\", \"CPU Requested\"=\"current_requested_cpu\", \"CPU Recommended\"=\"recommended_cpu\", \"CPU Diff\"=\"cpu_difference\",\"Memory Requested (MB)\"=\"current_requested_memory\",\"Memory Recommended (MB)\"=\"recommended_memory\",\"Memory Difference (MB)\"=\"memory_difference\"",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Workload Stats",
   "type": "table",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "columns": [
      { "selector": "workload_namespace", "text": "Namespace", "type": "string" },
      { "selector": "workload_name", "text": "Name", "type": "string" },
      { "selector": "container_name", "text": "Container", "type": "string" },
      {
       "selector": "cpu_usage_7_days",
       "text": "CPU usage 7d (pmax/p99/p90/p75/p50)",
       "type": "string"
      },
      { "selector": "spiky_ratio", "text": "Spiky Ratio", "type": "string" },
      {
       "selector": "contribution_to_total_requested",
       "text": "Contribution %",
       "type": "string"
      },
      { "selector": "priority", "text": "Priority", "type": "string" },
      { "selector": "autoscaling_on_cpu", "text": "CPU autoscaled", "type": "boolean" },
      { "selector": "workload_type", "text": "Type", "type": "string" }
     ],
     "parser": "uql",
     "source": "url",
     "type": "json",
     "uql": "parse-json \n| extend \"Workload\"=strcat(\"workload_type\", '/', \"workload_name\")\n| project \"Namespace\"=\"workload_namespace\", \"Workload\", \"Container\"=\"container_name\", \"CPU usage 7d (pmax/p99/p90/p75/p50)\"=\"cpu_usage_7_days\", \"Spike Range (predicted_max-p50_10min)\"=\"spike_range\", \"Owner Requested Gap\"=\"request_gap\", \"CPU autoscaled\"=\"autoscaling_on_cpu\", \"Blocking Karpenter\"=\"blocking_karpenter\"",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "OOM events count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "count(\n    (\n        kube_pod_container_status_last_terminated_reason{job=\"kube-state-metrics\",reason=\"OOMKilled\"}\n      * on (namespace, pod) group_left (node)\n        kube_pod_info{job=\"kube-state-metrics\"}\n    )\n  unless\n    sum by (node) (kube_node_status_allocatable{job=\"kube-state-metrics\",resource=\"nvidia_com_gpu\"} > 0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster load1 (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 90 },
   "targets": [
    {
     "expr": "sum(max(node_load1{job=\"node-exporter\"}) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n/ \nsum(max(kube_node_status_capacity{job=\"kube-state-metrics\", resource=\"cpu\"}) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n* 100",
     "legendFormat": "Avg cluster load (%)"
    },
    {
     "expr": "max((max(node_load1{job=\"node-exporter\"}) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n/ \n(max(kube_node_status_capacity{job=\"kube-state-metrics\", resource=\"cpu\"}) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n) * 100",
     "legendFormat": "Max across nodes (%)"
    },
    {
     "expr": "min((max(node_load1{job=\"node-exporter\"}) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n/ \n(max(kube_node_status_capacity{job=\"kube-state-metrics\", resource=\"cpu\"}) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n) * 100",
     "legendFormat": "Min across nodes (%)"
    }
   ]
  },
  {
   "title": "Cluster node cpu waiting %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 90 },
   "targets": [
    {
     "expr": "max(max(rate(node_pressure_cpu_waiting_seconds_total{job=\"node-exporter\"}[1m]) * 100) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n",
     "legendFormat": "Max waiting (%)"
    },
    {
     "expr": "avg(max(rate(node_pressure_cpu_waiting_seconds_total{job=\"node-exporter\"}[1m]) * 100) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n",
     "legendFormat": "Avg waiting (%)"
    }
   ]
  },
  {
   "title": "Throttle seconds rate / CPU seconds rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
   "targets": [
    {
     "expr": "(sum(sum(rate(container_cpu_cfs_throttled_seconds_total{job=\"kubelet\", container!=\"\"}[$__rate_interval])) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node)) / sum(sum(rate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\"}[$__rate_interval])) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node)))",
     "legendFormat": "Avg Throttle rate / CPU Usage"
    },
    {
     "expr": "max(sum(rate(container_cpu_cfs_throttled_seconds_total{job=\"kubelet\", container!=\"\"}[$__rate_interval])) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node) / sum(rate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\"}[$__rate_interval])) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))",
     "legendFormat": "Max Throttle rate / CPU Usage"
    },
    {
     "expr": "min(sum(rate(container_cpu_cfs_throttled_seconds_total{job=\"kubelet\", container!=\"\"}[$__rate_interval])) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node) / sum(rate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\"}[$__rate_interval])) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))",
     "legendFormat": "Min Throttle rate / CPU Usage"
    }
   ]
  },
  {
   "title": "Cluster node io pressure %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
   "targets": [
    {
     "expr": "max(max(rate(node_pressure_io_waiting_seconds_total{job=\"node-exporter\"}[1m]) * 100) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n",
     "legendFormat": "Max waiting (%)"
    },
    {
     "expr": "avg(max(rate(node_pressure_io_waiting_seconds_total{job=\"node-exporter\"}[1m]) * 100) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n",
     "legendFormat": "Avg waiting (%)"
    },
    {
     "expr": "max(max(rate(node_pressure_io_stalled_seconds_total{job=\"node-exporter\"}[1m]) * 100) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n",
     "legendFormat": "Max stalled (%)"
    },
    {
     "expr": "avg(max(rate(node_pressure_io_stalled_seconds_total{job=\"node-exporter\"}[1m]) * 100) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n",
     "legendFormat": "Avg stalled (%)"
    }
   ]
  },
  {
   "title": "Node idle CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 98 },
   "targets": [
    {
     "expr": "sum(sum(rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[$__rate_interval])) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n/ \nsum(max(kube_node_status_capacity{job=\"kube-state-metrics\", resource=\"cpu\"}) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n* 100",
     "legendFormat": "Avg cluster load (%)"
    },
    {
     "expr": "max((sum(rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[$__rate_interval])) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n/ \n(max(kube_node_status_capacity{job=\"kube-state-metrics\", resource=\"cpu\"}) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n* 100)",
     "legendFormat": "Max across nodes (%)"
    },
    {
     "expr": "min((sum(rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\"}[$__rate_interval])) by (node) unless on (node) sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n/ \n(max(kube_node_status_capacity{job=\"kube-state-metrics\", resource=\"cpu\"}) by (node) unless on (node) sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n* 100)",
     "legendFormat": "Min across nodes (%)"
    }
   ]
  },
  {
   "title": "Cluster node memory pressure %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 105 },
   "targets": [
    {
     "expr": "max(max(rate(node_pressure_memory_waiting_seconds_total{job=\"node-exporter\"}[1m]) * 100) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n",
     "legendFormat": "Max waiting (%)"
    },
    {
     "expr": "avg(max(rate(node_pressure_memory_waiting_seconds_total{job=\"node-exporter\"}[1m]) * 100) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n",
     "legendFormat": "Avg waiting (%)"
    },
    {
     "expr": "max(max(rate(node_pressure_memory_stalled_seconds_total{job=\"node-exporter\"}[1m]) * 100) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n",
     "legendFormat": "Max stalled (%)"
    },
    {
     "expr": "avg(max(rate(node_pressure_memory_stalled_seconds_total{job=\"node-exporter\"}[1m]) * 100) by (node) unless sum(kube_node_status_allocatable{resource=\"nvidia_com_gpu\", job=\"kube-state-metrics\"} == 1) by (node))\n",
     "legendFormat": "Avg stalled (%)"
    }
   ]
  },
  {
   "title": "OOM events count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_last_terminated_reason{reason=\"OOMKilled\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes undergoing pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 106 },
   "targets": [
    {
     "expr": "sum by (node, condition) (min_over_time(kube_node_status_condition{status!=\"false\", condition=~\"DiskPressure|MemoryPressure|PIDPressure\"}[2m:]) == 1)",
     "legendFormat": "{{condition}} - {{node}}"
    }
   ]
  }
 ]
}